//! Setup guide: per-platform, step-by-step instructions for importing a
//! generated config into the WireGuard client. Adapted from the legacy Vue
//! tutorial. Content is bilingual (en/de) inline — the images (served from
//! `public/tutorial-img/`, kept out of the `/tutorial` route path so the static
//! dir doesn't shadow it) are language-agnostic. Platform is chosen locally; the
//! language follows the app-wide i18n selection.

use dioxus::prelude::*;
use dioxus_i18n::{prelude::i18n, t};
use plan_ai_design::Card;

use crate::web::components::ui::PageHeader;

#[derive(Clone, Copy, PartialEq)]
enum Platform {
    Linux,
    Windows,
    Android,
}

/// One rendered block of a tutorial. Heading/Text/Link carry an i18n message
/// key (translated at render time via dioxus-i18n); Code and Img are
/// language-agnostic.
enum Block {
    Heading(&'static str),
    Text(&'static str),
    Code(&'static str),
    /// Language-agnostic image (full filename under `/tutorial-img/`) — the
    /// generic WireGuard-client screenshots.
    Img(&'static str),
    /// Language-specific screenshot of this app: the basename gets a `-en`/`-de`
    /// suffix + `.png` (regenerated by scripts/regen-tutorial-screenshots.sh).
    AppImg(&'static str),
    /// A prominent download/link button (i18n key label, external href).
    Link { key: &'static str, href: &'static str },
}

/// Pick English or German for the current language (default English). Used only
/// to select the language-specific app screenshots.
fn is_de() -> bool {
    i18n().language().to_string() == "de-DE"
}

#[component]
pub fn Tutorial() -> Element {
    let mut platform = use_signal(|| Platform::Windows);
    let de = is_de();
    let current = platform();

    rsx! {
        PageHeader { eyebrow: t!("nav-tutorial"), title: t!("tutorial-title"), subtitle: t!("tutorial-subtitle") }

        div { class: "flex gap-2 mb-6 flex-wrap",
            PlatformTab { label: t!("tutorial-platform-linux"), active: current == Platform::Linux,
                onclick: move |_| platform.set(Platform::Linux) }
            PlatformTab { label: t!("tutorial-platform-windows"), active: current == Platform::Windows,
                onclick: move |_| platform.set(Platform::Windows) }
            PlatformTab { label: t!("tutorial-platform-android"), active: current == Platform::Android,
                onclick: move |_| platform.set(Platform::Android) }
        }

        Card { class: "p-6",
            div { class: "flex flex-col gap-4 max-w-3xl",
                for (i, block) in blocks(current).into_iter().enumerate() {
                    match block {
                        Block::Heading(key) => rsx! {
                            h3 { key: "{i}", class: "text-lg font-semibold text-fg-strong mt-4", { i18n().translate(key) } }
                        },
                        Block::Text(key) => rsx! {
                            p { key: "{i}", class: "text-fg-muted text-sm leading-relaxed", { i18n().translate(key) } }
                        },
                        Block::Code(code) => rsx! {
                            pre { key: "{i}", class: "text-xs bg-surface-2 rounded-md p-3 overflow-x-auto whitespace-pre text-fg-strong", "{code}" }
                        },
                        Block::Img(name) => rsx! { Screenshot { key: "{i}", src: format!("/tutorial-img/{name}") } },
                        Block::AppImg(name) => rsx! {
                            Screenshot { key: "{i}", src: format!("/tutorial-img/{name}-{}.png", if de { "de" } else { "en" }) }
                        },
                        Block::Link { key, href } => rsx! {
                            a {
                                key: "{i}",
                                class: "self-start inline-flex items-center gap-2 rounded-lg bg-brand text-fg-invert text-sm font-medium px-4 py-2 shadow-card hover:opacity-90 transition-opacity no-underline",
                                href: "{href}",
                                target: "_blank",
                                rel: "noopener noreferrer",
                                { i18n().translate(key) }
                                span { class: "text-fg-invert/70", "↗" }
                            }
                        },
                    }
                }
            }
        }
    }
}

#[component]
fn PlatformTab(label: String, active: bool, onclick: EventHandler<MouseEvent>) -> Element {
    let cls = if active {
        "px-4 py-2 rounded-lg text-sm font-medium bg-brand text-fg-invert shadow-card"
    } else {
        "px-4 py-2 rounded-lg text-sm font-medium bg-surface-2 text-fg-muted hover:text-fg-strong transition-colors"
    };
    rsx! {
        button { class: "{cls}", onclick: move |e| onclick.call(e), "{label}" }
    }
}

#[component]
fn Screenshot(src: String) -> Element {
    rsx! {
        img {
            // self-start stops the flex column from stretching the image;
            // h-auto + max-w keep the aspect ratio intact.
            class: "rounded-lg border border-line shadow-card self-start h-auto w-auto max-w-full max-h-[480px]",
            src: "{src}",
            loading: "lazy",
            alt: "",
        }
    }
}

fn blocks(platform: Platform) -> Vec<Block> {
    match platform {
        Platform::Linux => linux(),
        Platform::Windows => windows(),
        Platform::Android => android(),
    }
}

// Shared opening steps: create a device on "My devices", then download the
// config. Strings live in the ftl files (keys below).
fn linux() -> Vec<Block> {
    vec![
        Block::Text("tut-create"),
        Block::AppImg("app-create-desktop"),
        Block::Text("tut-download"),
        Block::AppImg("app-config-desktop"),
        Block::Text("tut-linux-save"),
        Block::Heading("tut-nm"),
        Block::Text("tut-linux-nm-intro"),
        Block::Code("nmcli conn import type wireguard file wg0-laptop.conf\nnmcli conn mod wg0-laptop ipv6.route-metric 9000\n# start it\nnmcli c u wg0-laptop"),
        Block::Text("tut-linux-nm-reboot"),
        Block::Heading("tut-tools"),
        Block::Text("tut-linux-tools-intro"),
        Block::Code("sudo mkdir -p /etc/wireguard\nsudo cp wg0-laptop.conf /etc/wireguard/\nsudo wg-quick up wg0-laptop"),
        Block::Text("tut-linux-tools-reboot"),
    ]
}

fn windows() -> Vec<Block> {
    vec![
        Block::Text("tut-create"),
        Block::AppImg("app-create-desktop"),
        Block::Text("tut-download"),
        Block::AppImg("app-config-desktop"),
        Block::Text("tut-win-install"),
        Block::Link { key: "tut-win-download-link", href: "https://www.wireguard.com/install/" },
        Block::Img("win-wireguard-com.png"),
        Block::Text("tut-win-open-file"),
        Block::Img("win-wireguard-com-dl2.png"),
        Block::Img("win-wireguard-smartscreen.png"),
        Block::Text("tut-win-import"),
        Block::Img("win-wireguard-open.png"),
        Block::Text("tut-win-select"),
        Block::Img("win-wireguard-file-select.png"),
        Block::Text("tut-win-edit"),
        Block::Img("win-wireguard-edit.png"),
        Block::Text("tut-win-killswitch"),
        Block::Img("win-wireguard-edit2.png"),
        Block::Text("tut-win-activate"),
        Block::Img("win-wireguard-activate.png"),
        Block::Img("win-wireguard-activate2.png"),
        Block::Text("tut-win-done"),
    ]
}

fn android() -> Vec<Block> {
    vec![
        Block::Text("tut-create"),
        Block::AppImg("app-create-mobile"),
        Block::Text("tut-android-download"),
        Block::AppImg("app-config-mobile"),
        Block::Text("tut-android-install"),
        Block::Link { key: "tut-android-download-link", href: "https://play.google.com/store/apps/details?id=com.wireguard.android" },
        Block::Img("android-wireguard-playstore.png"),
        Block::Text("tut-android-open"),
        Block::Img("android-wireguard-playstore-installed.png"),
        Block::Text("tut-android-plus"),
        Block::Img("android-wireguard-open.png"),
        Block::Text("tut-android-import"),
        Block::Img("android-wireguard-import.png"),
        Block::Text("tut-android-pick"),
        Block::Img("android-wireguard-import-1.png"),
        Block::Text("tut-android-activate"),
    ]
}

