//! Setup guide: per-platform, step-by-step instructions for importing a
//! generated config into the WireGuard client. Adapted from the legacy Vue
//! tutorial. Content is bilingual (en/de) inline — the images (served from
//! `public/tutorial-img/`, kept out of the `/tutorial` route path so the static
//! dir doesn't shadow it) are language-agnostic. Platform is chosen locally; the
//! language follows the app-wide i18n selection.

use dioxus::prelude::*;
use dioxus_i18n::{prelude::i18n, t};
use plan_ai_design::Card;

use crate::web::components::ui::PageHeader;

#[derive(Clone, Copy, PartialEq)]
enum Platform {
    Linux,
    Windows,
    Android,
}

/// One rendered block of a tutorial. Text/Heading are bilingual; Code and Img
/// are the same regardless of language.
enum Block {
    Heading { en: &'static str, de: &'static str },
    Text { en: &'static str, de: &'static str },
    Code(&'static str),
    /// Language-agnostic image (full filename under `/tutorial-img/`) — the
    /// generic WireGuard-client screenshots.
    Img(&'static str),
    /// Language-specific screenshot of this app: the basename gets a `-en`/`-de`
    /// suffix + `.png` (regenerated by scripts/regen-tutorial-screenshots.sh).
    AppImg(&'static str),
    /// A prominent download/link button (bilingual label, external href).
    Link { en: &'static str, de: &'static str, href: &'static str },
}

/// Pick English or German for the current language (default English).
fn is_de() -> bool {
    i18n().language().to_string() == "de-DE"
}

#[component]
pub fn Tutorial() -> Element {
    let mut platform = use_signal(|| Platform::Windows);
    let de = is_de();
    let current = platform();

    rsx! {
        PageHeader { eyebrow: t!("nav-tutorial"), title: t!("tutorial-title"), subtitle: t!("tutorial-subtitle") }

        div { class: "flex gap-2 mb-6 flex-wrap",
            PlatformTab { label: t!("tutorial-platform-linux"), active: current == Platform::Linux,
                onclick: move |_| platform.set(Platform::Linux) }
            PlatformTab { label: t!("tutorial-platform-windows"), active: current == Platform::Windows,
                onclick: move |_| platform.set(Platform::Windows) }
            PlatformTab { label: t!("tutorial-platform-android"), active: current == Platform::Android,
                onclick: move |_| platform.set(Platform::Android) }
        }

        Card { class: "p-6",
            div { class: "flex flex-col gap-4 max-w-3xl",
                for (i, block) in blocks(current).into_iter().enumerate() {
                    match block {
                        Block::Heading { en, de: d } => rsx! {
                            h3 { key: "{i}", class: "text-lg font-semibold text-fg-strong mt-4", { if de { d } else { en } } }
                        },
                        Block::Text { en, de: d } => rsx! {
                            p { key: "{i}", class: "text-fg-muted text-sm leading-relaxed", { if de { d } else { en } } }
                        },
                        Block::Code(code) => rsx! {
                            pre { key: "{i}", class: "text-xs bg-surface-2 rounded-md p-3 overflow-x-auto whitespace-pre text-fg-strong", "{code}" }
                        },
                        Block::Img(name) => rsx! { Screenshot { key: "{i}", src: format!("/tutorial-img/{name}") } },
                        Block::AppImg(name) => rsx! {
                            Screenshot { key: "{i}", src: format!("/tutorial-img/{name}-{}.png", if de { "de" } else { "en" }) }
                        },
                        Block::Link { en, de: d, href } => rsx! {
                            a {
                                key: "{i}",
                                class: "self-start inline-flex items-center gap-2 rounded-lg bg-brand text-fg-invert text-sm font-medium px-4 py-2 shadow-card hover:opacity-90 transition-opacity no-underline",
                                href: "{href}",
                                target: "_blank",
                                rel: "noopener noreferrer",
                                { if de { d } else { en } }
                                span { class: "text-fg-invert/70", "↗" }
                            }
                        },
                    }
                }
            }
        }
    }
}

#[component]
fn PlatformTab(label: String, active: bool, onclick: EventHandler<MouseEvent>) -> Element {
    let cls = if active {
        "px-4 py-2 rounded-lg text-sm font-medium bg-brand text-fg-invert shadow-card"
    } else {
        "px-4 py-2 rounded-lg text-sm font-medium bg-surface-2 text-fg-muted hover:text-fg-strong transition-colors"
    };
    rsx! {
        button { class: "{cls}", onclick: move |e| onclick.call(e), "{label}" }
    }
}

#[component]
fn Screenshot(src: String) -> Element {
    rsx! {
        img {
            // self-start stops the flex column from stretching the image;
            // h-auto + max-w keep the aspect ratio intact.
            class: "rounded-lg border border-line shadow-card self-start h-auto w-auto max-w-full max-h-[480px]",
            src: "{src}",
            loading: "lazy",
            alt: "",
        }
    }
}

fn blocks(platform: Platform) -> Vec<Block> {
    match platform {
        Platform::Linux => linux(),
        Platform::Windows => windows(),
        Platform::Android => android(),
    }
}

// Shared opening steps: create a device on "My devices", then download the
// config. The button labels match the app UI.
const CREATE_EN: &str =
    "On the \"My devices\" page, pick the interface you want, type a name for this device (e.g. \"laptop\") and click Generate.";
const CREATE_DE: &str =
    "Wähle auf der Seite \"Meine Geräte\" die gewünschte Schnittstelle, gib einen Namen für das Gerät ein (z. B. \"laptop\") und klicke auf \"Erstellen\".";
const DOWNLOAD_EN: &str =
    "Your configuration appears. Click Download to save the .conf file (named after the interface and your device). Save it now — it can't be shown again.";
const DOWNLOAD_DE: &str =
    "Deine Konfiguration erscheint. Klicke auf \"Herunterladen\", um die .conf-Datei zu speichern (benannt nach Schnittstelle und Gerät). Jetzt speichern — sie wird nicht erneut angezeigt.";

fn linux() -> Vec<Block> {
    vec![
        Block::Text { en: CREATE_EN, de: CREATE_DE },
        Block::AppImg("app-create-desktop"),
        Block::Text { en: DOWNLOAD_EN, de: DOWNLOAD_DE },
        Block::AppImg("app-config-desktop"),
        Block::Text {
            en: "Save the file in your home directory, then open a terminal. If it was saved elsewhere, change into that directory with `cd` (e.g. `cd Downloads`). The commands below use the name of the file you downloaded (shown here as `wg0-laptop.conf`) — substitute yours. Below are two methods — pick one and follow it.",
            de: "Speichere die Datei am besten im Home-Verzeichnis und öffne ein Terminal. Liegt die Datei woanders, wechsle mit `cd` dorthin (z. B. `cd Downloads`). Die Befehle unten verwenden den Namen deiner heruntergeladenen Datei (hier `wg0-laptop.conf`) — ersetze ihn durch deinen. Unten findest du zwei Methoden — wähle eine und folge ihr.",
        },
        Block::Heading { en: "NetworkManager", de: "NetworkManager" },
        Block::Text {
            en: "If your distribution uses NetworkManager, import and activate the config with:",
            de: "Falls deine Distribution NetworkManager verwendet, importiere und aktiviere die Konfiguration so:",
        },
        Block::Code("nmcli conn import type wireguard file wg0-laptop.conf\nnmcli conn mod wg0-laptop ipv6.route-metric 9000\n# start it\nnmcli c u wg0-laptop"),
        Block::Text {
            en: "The connection is re-established automatically after a reboot.",
            de: "Die Verbindung wird nach Neustarts automatisch wiederhergestellt.",
        },
        Block::Heading { en: "WireGuard tools", de: "WireGuard Tools" },
        Block::Text {
            en: "If your network is not managed by NetworkManager, use wireguard-tools (install the `wireguard-tools` package for your distribution), then run:",
            de: "Verwaltet deine Distribution das Netzwerk nicht über NetworkManager, nutze wireguard-tools (installiere das Paket `wireguard-tools`), und führe dann aus:",
        },
        Block::Code("sudo mkdir -p /etc/wireguard\nsudo cp wg0-laptop.conf /etc/wireguard/\nsudo wg-quick up wg0-laptop"),
        Block::Text {
            en: "After a reboot you may need to bring the connection up again with `sudo wg-quick up wg0-laptop`.",
            de: "Nach einem Neustart musst du die Verbindung eventuell erneut mit `sudo wg-quick up wg0-laptop` herstellen.",
        },
    ]
}

fn windows() -> Vec<Block> {
    vec![
        Block::Text { en: CREATE_EN, de: CREATE_DE },
        Block::AppImg("app-create-desktop"),
        Block::Text { en: DOWNLOAD_EN, de: DOWNLOAD_DE },
        Block::AppImg("app-config-desktop"),
        Block::Text {
            en: "Now install the WireGuard software: download it from wireguard.com and choose the Windows version.",
            de: "Installiere nun die WireGuard-Software: Lade sie von wireguard.com herunter und wähle die Windows-Version.",
        },
        Block::Link {
            en: "Download WireGuard for Windows",
            de: "WireGuard für Windows herunterladen",
            href: "https://www.wireguard.com/install/",
        },
        Block::Img("win-wireguard-com.png"),
        Block::Text {
            en: "After downloading, open the file and accept the security prompt.",
            de: "Öffne die heruntergeladene Datei und bestätige die Sicherheitsmeldung.",
        },
        Block::Img("win-wireguard-com-dl2.png"),
        Block::Img("win-wireguard-smartscreen.png"),
        Block::Text {
            en: "WireGuard should open automatically after installation. If not, just open the WireGuard app from the search. In the WireGuard window, choose \"Import tunnel(s) from file\".",
            de: "WireGuard sollte sich nach der Installation automatisch öffnen. Falls nicht, öffne die App WireGuard über die Suche. Wähle im WireGuard-Fenster \"Tunnel aus Datei importieren\".",
        },
        Block::Img("win-wireguard-open.png"),
        Block::Text {
            en: "Select the file and confirm with \"Open\".",
            de: "Wähle die Datei aus und bestätige mit \"Öffnen\".",
        },
        Block::Img("win-wireguard-file-select.png"),
        Block::Text {
            en: "After importing, edit the connection.",
            de: "Bearbeite anschließend die Verbindung.",
        },
        Block::Img("win-wireguard-edit.png"),
        Block::Text {
            en: "Disable the option \"Block untunneled traffic (kill-switch)\" and confirm.",
            de: "Deaktiviere die Option \"Verkehr außerhalb des Tunnels blockieren\" und bestätige.",
        },
        Block::Img("win-wireguard-edit2.png"),
        Block::Text {
            en: "Then activate the tunnel.",
            de: "Aktiviere danach den Tunnel.",
        },
        Block::Img("win-wireguard-activate.png"),
        Block::Img("win-wireguard-activate2.png"),
        Block::Text {
            en: "The tunnel is now active. It reconnects automatically after a reboot.",
            de: "Der Tunnel ist jetzt aktiv und wird nach einem Neustart automatisch neu gestartet.",
        },
    ]
}

fn android() -> Vec<Block> {
    vec![
        Block::Text { en: CREATE_EN, de: CREATE_DE },
        Block::AppImg("app-create-mobile"),
        Block::Text {
            en: "Your configuration appears. Download the .conf file — or, quicker on a phone, scan the QR code directly from the WireGuard app (see below).",
            de: "Deine Konfiguration erscheint. Lade die .conf-Datei herunter — oder scanne am Handy einfach den QR-Code direkt aus der WireGuard-App (siehe unten).",
        },
        Block::AppImg("app-config-mobile"),
        Block::Text {
            en: "Now install the WireGuard app from the Play Store.",
            de: "Installiere nun die WireGuard-App aus dem Play Store.",
        },
        Block::Link {
            en: "Get WireGuard on Google Play",
            de: "WireGuard bei Google Play holen",
            href: "https://play.google.com/store/apps/details?id=com.wireguard.android",
        },
        Block::Img("android-wireguard-playstore.png"),
        Block::Text {
            en: "Open the app.",
            de: "Öffne die App.",
        },
        Block::Img("android-wireguard-playstore-installed.png"),
        Block::Text {
            en: "Tap the plus button at the bottom right.",
            de: "Tippe unten rechts auf das Plus-Zeichen.",
        },
        Block::Img("android-wireguard-open.png"),
        Block::Text {
            en: "Choose \"Import from file or archive\".",
            de: "Wähle \"Aus Datei oder Archiv importieren\".",
        },
        Block::Img("android-wireguard-import.png"),
        Block::Text {
            en: "Pick Downloads, then the .conf file you downloaded.",
            de: "Wähle Downloads und dann die heruntergeladene .conf-Datei.",
        },
        Block::Img("android-wireguard-import-1.png"),
        Block::Text {
            en: "Activate the tunnel.",
            de: "Aktiviere den Tunnel.",
        },
    ]
}

